# Generated by Django 5.2.2 on 2025-06-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0002_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
