# Generated by Django 5.2.1 on 2025-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0006_remove_doctor_email_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='estado_switch',
            field=models.CharField(default='desactivado', max_length=20),
        ),
    ]
