# Generated by Django 5.2.1 on 2025-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0008_alter_doctor_estado_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='estado_switch',
            field=models.CharField(default='No acepta nuevos pacientes', max_length=20),
        ),
    ]
