# Generated by Django 5.2.1 on 2025-06-17 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0009_alter_doctor_estado_switch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='password',
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_quirurgicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_vacunacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
