# Generated by Django 5.2.1 on 2025-06-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0010_remove_paciente_email_remove_paciente_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historial_vacunacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='medicamentos_actuales',
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='antecedentes_quirurgicos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedades',
            field=models.TextField(blank=True),
        ),
    ]
