# Generated by Django 5.2.1 on 2025-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0011_remove_paciente_historial_vacunacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.TextField(blank=True),
        ),
    ]
