# Generated by Django 5.2.1 on 2025-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0013_alter_paciente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Aseguradora',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Datos_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='horacita',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_visita',
            field=models.TextField(blank=True),
        ),
    ]
