# Generated by Django 5.2.1 on 2025-06-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0014_paciente_aseguradora_paciente_datos_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevosPacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('datos_consulta', models.TextField(blank=True)),
                ('motivo_visita', models.TextField(blank=True)),
                ('aseguradora', models.TextField(blank=True)),
                ('horacita', models.TextField(blank=True)),
            ],
        ),
    ]
