# Generated by Django 5.2.1 on 2025-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0015_nuevospacientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuevospacientes',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.TextField(blank=True),
        ),
    ]
