# Generated by Django 5.2.1 on 2025-06-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0016_remove_nuevospacientes_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Aseguradora',
            new_name='aseguradora',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Datos_consulta',
            new_name='datos_consulta',
        ),
    ]
