# Generated by Django 5.2.1 on 2025-06-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0018_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='creada_en',
        ),
    ]
