# Generated by Django 5.2.1 on 2025-06-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0019_remove_cita_creada_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nombre_doctor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helcon.paciente'),
        ),
    ]
