# Generated by Django 5.2.1 on 2025-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0020_cita_nombre_doctor_cita_nombre_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='nombre_doctor',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre_paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
