# Generated by Django 5.2.1 on 2025-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0021_remove_cita_nombre_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor_nombre',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
