# Generated by Django 5.2.1 on 2025-06-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0022_cita_doctor_nombre_alter_cita_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nuevospacientes',
            name='fecha_cita',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_cita',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
