# Generated by Django 5.2.1 on 2025-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0023_cita_fecha_cita_nuevospacientes_fecha_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nuevospacientes',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_cita',
            field=models.DateField(blank=True, null=True),
        ),
    ]
