# Generated by Django 5.2.1 on 2025-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0024_alter_cita_fecha_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevospacientes',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
