# Generated by Django 5.2.1 on 2025-06-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0025_nuevospacientes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
