# Generated by Django 5.2.1 on 2025-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0026_cita_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(default='No confimada', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
