# Generated by Django 5.2.3 on 2025-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0027_cita_estado_cita_alter_cita_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado_cita',
            field=models.CharField(default='No confirmada', max_length=20),
        ),
    ]
