# Generated by Django 5.2.3 on 2025-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0028_alter_cita_estado_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='recomendado',
            field=models.CharField(default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cupon',
            field=models.TextField(blank=True),
        ),
    ]
