# Generated by Django 5.2.3 on 2025-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0029_doctor_recomendado_paciente_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cupon',
            field=models.TextField(blank=True, default='si'),
        ),
    ]
