# Generated by Django 5.2.3 on 2025-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0030_alter_paciente_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='recomendado',
            field=models.CharField(blank=True, default='no', max_length=20),
        ),
    ]
