# Generated by Django 5.2.1 on 2025-07-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helcon', '0031_alter_doctor_recomendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='preciobase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
